[package]
name = "basecamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powershell_script = "1.1.0"
winapi = { version = "0.3.9", features = ["winuser"] }
