[package]
name = "keybinder"
version = "0.1.0"
edition = "2021"

[dependencies]
powershell_script = "1.1.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
winapi = { version = "0.3.9", features = ["winuser"] }
winit = "0.29.10"
